/**
 * Zebra USB Printer Module
 * Direct printing to Zebra printers via WebUSB API (browser-only, no server required)
 */

const ZEBRA_VENDOR_ID = 0x0A5F; // Common Zebra vendor ID

/**
 * Request access to a Zebra USB printer
 * Shows browser's USB device picker dialog
 * @returns Opened and configured USB device
 */
export async function requestZebraDevice(): Promise<USBDevice> {
  // Check WebUSB support
  if (!("usb" in navigator)) {
    throw new Error("WebUSB is not supported in this browser. Please use Chrome or Edge on desktop.");
  }

  try {
    // Request device with Zebra filter (allows all devices if Zebra not found)
    const device = await navigator.usb!.requestDevice({
      filters: [
        { vendorId: ZEBRA_VENDOR_ID }, // Zebra printers
        // Allow all USB devices as fallback (some Zebra models may use different vendor IDs)
      ],
    });

    // Open the device
    await device.open();

    // Select configuration (skip if already selected)
    const deviceAny = device as any;
    if (!deviceAny.configuration) {
      await device.selectConfiguration(1);
    }

    // Claim interface 0 (standard for printers)
    await device.claimInterface(0);

    return device;
  } catch (error) {
    if ((error as Error).name === "NotFoundError") {
      throw new Error("No USB device selected. Please select your Zebra printer.");
    }
    throw error;
  }
}

/**
 * Send raw ZPL code to the printer
 * @param device Opened USB device
 * @param zplString Raw ZPL string (exactly as generated by Export with Field Values)
 */
export async function sendZPL(device: USBDevice, zplString: string): Promise<void> {
  try {
    // Convert ZPL string to ASCII bytes (8-bit, no UTF-16)
    const encoder = new TextEncoder();
    const data = encoder.encode(zplString);

    // Find the first OUT endpoint
    // TODO: If the printer does not use OUT endpoint 1, detect the correct OUT endpoint dynamically.
    let endpointNumber = 1; // Default to endpoint 1 for most Zebra printers

    // Try to detect OUT endpoint dynamically
    const deviceAny = device as any;
    if (deviceAny.configuration?.interfaces) {
      for (const iface of deviceAny.configuration.interfaces) {
        for (const alt of iface.alternates) {
          for (const endpoint of alt.endpoints) {
            if (endpoint.direction === "out") {
              endpointNumber = endpoint.endpointNumber;
              break;
            }
          }
        }
      }
    }

    // Send raw ZPL data to printer
    const result = await device.transferOut(endpointNumber, data);

    if (result.status !== "ok") {
      throw new Error(`USB transfer failed with status: ${result.status}`);
    }

    console.log(`Successfully sent ${result.bytesWritten} bytes to printer`);
  } catch (error) {
    console.error("Failed to send ZPL to printer:", error);
    throw new Error("Print failed. Check USB connection and that the printer is powered on.");
  }
}

/**
 * Close the USB device connection
 * @param device USB device to close
 */
export async function closeDevice(device: USBDevice | null): Promise<void> {
  if (!device) return;
  
  try {
    await device.close();
  } catch (error) {
    console.error("Error closing USB device:", error);
  }
}

// TODO: Support multiple connected printers / let user pick which Zebra device to use.
// TODO: Auto-reconnect if USB is unplugged and then plugged back in.
